disabled_rules: # rule identifiers to exclude from running
  - line_length
  - cyclomatic_complexity
 
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
  - *.framework
 