# No disabled or configured rules, so that all all problems are solved inline.
# The user of this code might have a different set of rules.

disabled_rules: # rule identifiers to exclude from running
